# Generated by Django 5.1.2 on 2024-10-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descripcion',
            new_name='description',
        ),
    ]
